
package client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.7-b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WeatherEndpointService", targetNamespace = "http://server/", wsdlLocation = "http://localhost:8081/weather?wsdl")
public class WeatherEndpointService
    extends Service
{

    private final static URL WEATHERENDPOINTSERVICE_WSDL_LOCATION;
    private final static WebServiceException WEATHERENDPOINTSERVICE_EXCEPTION;
    private final static QName WEATHERENDPOINTSERVICE_QNAME = new QName("http://server/", "WeatherEndpointService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8081/weather?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WEATHERENDPOINTSERVICE_WSDL_LOCATION = url;
        WEATHERENDPOINTSERVICE_EXCEPTION = e;
    }

    public WeatherEndpointService() {
        super(__getWsdlLocation(), WEATHERENDPOINTSERVICE_QNAME);
    }

    public WeatherEndpointService(WebServiceFeature... features) {
        super(__getWsdlLocation(), WEATHERENDPOINTSERVICE_QNAME, features);
    }

    public WeatherEndpointService(URL wsdlLocation) {
        super(wsdlLocation, WEATHERENDPOINTSERVICE_QNAME);
    }

    public WeatherEndpointService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WEATHERENDPOINTSERVICE_QNAME, features);
    }

    public WeatherEndpointService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WeatherEndpointService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WeatherEndpoint
     */
    @WebEndpoint(name = "WeatherEndpointPort")
    public WeatherEndpoint getWeatherEndpointPort() {
        return super.getPort(new QName("http://server/", "WeatherEndpointPort"), WeatherEndpoint.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WeatherEndpoint
     */
    @WebEndpoint(name = "WeatherEndpointPort")
    public WeatherEndpoint getWeatherEndpointPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://server/", "WeatherEndpointPort"), WeatherEndpoint.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WEATHERENDPOINTSERVICE_EXCEPTION!= null) {
            throw WEATHERENDPOINTSERVICE_EXCEPTION;
        }
        return WEATHERENDPOINTSERVICE_WSDL_LOCATION;
    }

}
